require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TunesController do

  # This should return the minimal set of attributes required to create a valid
  # Tune. As you add validations to Tune, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TunesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tunes as @tunes" do
      tune = Tune.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tunes).should eq([tune])
    end
  end

  describe "GET show" do
    it "assigns the requested tune as @tune" do
      tune = Tune.create! valid_attributes
      get :show, {:id => tune.to_param}, valid_session
      assigns(:tune).should eq(tune)
    end
  end

  describe "GET new" do
    it "assigns a new tune as @tune" do
      get :new, {}, valid_session
      assigns(:tune).should be_a_new(Tune)
    end
  end

  describe "GET edit" do
    it "assigns the requested tune as @tune" do
      tune = Tune.create! valid_attributes
      get :edit, {:id => tune.to_param}, valid_session
      assigns(:tune).should eq(tune)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tune" do
        expect {
          post :create, {:tune => valid_attributes}, valid_session
        }.to change(Tune, :count).by(1)
      end

      it "assigns a newly created tune as @tune" do
        post :create, {:tune => valid_attributes}, valid_session
        assigns(:tune).should be_a(Tune)
        assigns(:tune).should be_persisted
      end

      it "redirects to the created tune" do
        post :create, {:tune => valid_attributes}, valid_session
        response.should redirect_to(Tune.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tune as @tune" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tune.any_instance.stub(:save).and_return(false)
        post :create, {:tune => {}}, valid_session
        assigns(:tune).should be_a_new(Tune)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tune.any_instance.stub(:save).and_return(false)
        post :create, {:tune => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tune" do
        tune = Tune.create! valid_attributes
        # Assuming there are no other tunes in the database, this
        # specifies that the Tune created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tune.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tune.to_param, :tune => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tune as @tune" do
        tune = Tune.create! valid_attributes
        put :update, {:id => tune.to_param, :tune => valid_attributes}, valid_session
        assigns(:tune).should eq(tune)
      end

      it "redirects to the tune" do
        tune = Tune.create! valid_attributes
        put :update, {:id => tune.to_param, :tune => valid_attributes}, valid_session
        response.should redirect_to(tune)
      end
    end

    describe "with invalid params" do
      it "assigns the tune as @tune" do
        tune = Tune.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tune.any_instance.stub(:save).and_return(false)
        put :update, {:id => tune.to_param, :tune => {}}, valid_session
        assigns(:tune).should eq(tune)
      end

      it "re-renders the 'edit' template" do
        tune = Tune.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tune.any_instance.stub(:save).and_return(false)
        put :update, {:id => tune.to_param, :tune => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tune" do
      tune = Tune.create! valid_attributes
      expect {
        delete :destroy, {:id => tune.to_param}, valid_session
      }.to change(Tune, :count).by(-1)
    end

    it "redirects to the tunes list" do
      tune = Tune.create! valid_attributes
      delete :destroy, {:id => tune.to_param}, valid_session
      response.should redirect_to(tunes_url)
    end
  end

end
